import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AppProviders from "@/providers/AppProviders";
import Footer from "@/components/Footer";
import Script from "next/script";
import { Toaster } from "react-hot-toast";
import FloatingCallButton from "@/components/FloatingCallButton";
import FloatingWhatsApp from "@/components/FloatingWhatsApp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
        <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="beforeInteractive" />
        <AppProviders>
          <Navbar />
          <div className="lg:mt-44 md:mt-[180px] mt-[60px]">
            {children}
          </div>
          <Toaster position="top-right" />
          <Footer />
        </AppProviders>
        {/* <FloatingCallButton /> */}
        {/* <FloatingWhatsApp /> */}
      </body>
    </html>
  );
}
